### ISSUE TITLE
아직업데이트중이신가요

### ISSUE THREAD

**Issue by hhp9508** [prunusnira/priconne-clan-battle-client#1]
사이트 구동절차 알려주실수잇나해서 남깁니다..

**Comment by prunusnira** [comment]
안녕하세요.

이 프로젝트는 아직 초기단계이고 상세한 기능이 제작된 상태가 아닙니다.
그렇다고 프로젝트를 포기한건 아니고 회사 일이나 다른 개인적인 프로젝트들로 인해 잠시 멈춰져있는 상태입니다.

구동을 위해서는 별도의 DB가 필요합니다. DB접속 정보 및 스키마 정보는 이 repo에서는 빠져있는 상태입니다.
단순 구동을 위해서는 별도의 mysql 혹은 mariadb 기반의 db를 구축하신 뒤 server를 npx tsc로 빌드하신 후 node로 가동하시면 됩니다.

이와 별개로 본 프로젝트가 완성되면 URL을 제공할 예정입니다.
감사합니다.

**Comment by hhp9508** [comment]
감사합니다 기다리겟습니다~ 피드백 빠르시네요
